/*
SQL ran in GDC
SELECT charachters.feature FROM
  (SELECT COUNT(*) AS featureCount, s.feature
  FROM gcd_story s
  WHERE (feature <> "" ) AND (feature NOT LIKE ("%[%]%"))
  GROUP BY s.feature
  ORDER BY featureCount DESC LIMIT 500 ) AS charachters
ORDER BY feature ASC;

Then select and copy all rows results to
https://convert.town/column-to-comma-separated-list
and format to get commas, then paste in here.
*/

const charactersList = [
  "100 Bullets",
  "100 Toy Soldiers",
  "?",
  "Adam Strange",
  "Adventure Time",
  "Agent 327",
  "Airboy",
  "Alan Ford",
  "Alf",
  "Aliens",
  "Alle Hjems Vareservice",
  "Alpha Flight",
  "American Body Building Club",
  "American Seed Co.",
  "American Splendor",
  "Andy Capp",
  "Andy Panda",
  "Angel",
  "Aquaman",
  "Archie",
  "Archie & Friends",
  "Archie and Me",
  "Archie and the Gang",
  "Archie Club",
  "Archie Club News",
  "Archie's Gag Bag",
  "Argus",
  "Art Instruction, Inc.",
  "Asterix",
  "Astro City",
  "Avengers",
  "B.P.R.D.",
  "Baby Ruth",
  "Barbie",
  "Batgirl",
  "Batman",
  "Batman and Robin",
  "Batman with Robin the Boy Wonder",
  "Batman; Robin",
  "Battlestar Galactica",
  "Batwoman",
  "Beep Beep the Road Runner",
  "Beestjes",
  "Beetle Bailey",
  "Bernard Prince",
  "Betty",
  "Betty and Me",
  "Betty and Veronica",
  "Big Moose",
  "Billie Turf",
  "Billy the Kid",
  "Binky",
  "Birds of Prey",
  "Bizarro",
  "Black Cat",
  "Black Panther",
  "Black Widow",
  "Blackhawk",
  "Bleach",
  "Blondie",
  "Bloodshot",
  "Blue Beetle",
  "Blueberry",
  "Boes",
  "Bone",
  "Brick Bradford",
  "Buck Danny",
  "Buck Jones",
  "Buffalo Bill",
  "Buffy the Vampire Slayer",
  "Bugs Bunny",
  "Bullpen Bulletins",
  "Buzzy",
  "Cable",
  "Cap's Hobby Hints",
  "Capitan Miki",
  "Captain America",
  "Captain Atom",
  "Captain Marvel",
  "Captain Marvel, Jr.",
  "Captain Midnight",
  "Captain Tootsie; Tootsie Roll",
  "Case Closed",
  "Casey the Cop",
  "Casper",
  "Casper the Friendly Ghost",
  "Cathy",
  "Catwoman",
  "Cerebus",
  "Challengers of the Unknown",
  "Channel 52",
  "Charles Atlas",
  "Chew",
  "Cheyenne Kid",
  "Chip 'n' Dale",
  "Cicero's Cat",
  "Claire",
  "Conan",
  "Conan barbaren",
  "Conan el Bárbaro",
  "Conan the Barbarian",
  "Corto Maltese",
  "Crossed",
  "Daffy Duck",
  "Dagwood",
  "Daily Planet",
  "Daisy Air Rifles",
  "Daisy Manufacturing Company",
  "Dan Dare",
  "Daredevil",
  "Dating for geeks",
  "Davy Crockett",
  "DC All Access",
  "DC Comics",
  "DC Comics All Access",
  "DC In Demand",
  "DC Nation",
  "Deadpool",
  "Deathstroke",
  "Defenders",
  "Den velkjente soldat",
  "Dennis the Menace",
  "Diabolik",
  "Dick Tracy",
  "Dilbert",
  "Dilton",
  "Direct Currents",
  "Dirkjan",
  "Doc Savage",
  "Doctor Strange",
  "Doctor Who",
  "Doll Man",
  "Don Martin Dept.",
  "Donald Duck",
  "Donald pocket",
  "Doom Patrol",
  "Dr. Strange",
  "Dracula",
  "Droopy",
  "Dubble Bubble",
  "Dylan Dog",
  "Editor's Notebook",
  "Elektra",
  "Elfquest",
  "Elsje",
  "Eon",
  "Ernie",
  "Eugene",
  "Excalibur",
  "Fables",
  "Fairy Tail",
  "Family Circus",
  "Fantastic Four",
  "Fantomen",
  "Fantomet",
  "Fantometklubben",
  "Fat Freddy's Cat",
  "FC Knudde",
  "Felix the Cat",
  "Flash",
  "Flash Gordon",
  "Flintstones",
  "Fokke & Sukke",
  "Franka",
  "Freak Brothers",
  "G. I. Joe",
  "G.I. Joe",
  "Gadget",
  "Garcelon Stamp Co.",
  "Garfield",
  "Gene Autry",
  "Ghost Rider",
  "Ghostbusters",
  "Godzilla",
  "Gold Digger",
  "Goofy",
  "Green Arrow",
  "Green Hornet",
  "Green Lantern",
  "Green Lantern Corps",
  "Grimm Fairy Tales",
  "Guardians of the Galaxy",
  "Gyro Gearloose",
  "Hara Kiwi",
  "Harbinger",
  "Harley Quinn",
  "Hawkeye",
  "Hawkman",
  "Heathcliff",
  "Heckle and Jeckle",
  "Heinz de kat",
  "Hellblazer",
  "Hellboy",
  "Henry",
  "Hercule",
  "Hercules",
  "Herman Hedning & Co",
  "Heroic True Life Story",
  "Hodepine",
  "Hombre-Araña",
  "Hopalong Cassidy",
  "Horsepower",
  "Howard the Duck",
  "Hulk",
  "Human Torch",
  "Il Grande Blek",
  "Inhumans",
  "InuYasha",
  "Invincible",
  "Iron Fist",
  "Iron Man",
  "James Bond",
  "Jan, Jans en de kinderen",
  "Jimmy Olsen",
  "Joe Palooka",
  "Johnny Hazard",
  "Jonah Hex",
  "Josie",
  "Josie and the Pussycats",
  "Journal des jeux",
  "Jowett Institute of Physical Training",
  "Judge Dredd",
  "Jughead",
  "Jukan",
  "Junior Sales Club of America",
  "Junior Woodchucks",
  "Justice League",
  "Justice League of America",
  "Justice Society of America",
  "Ka-Zar",
  "Kalle Anka",
  "Kamp-serien",
  "Katy Keene",
  "Keys of Knowledge",
  "Kid Colt",
  "Kid Colt Outlaw",
  "Kit Carson",
  "Knights of the Dinner Table",
  "Kollektivet",
  "Korak",
  "Korak Tarzans sønn",
  "Krazy Kat",
  "Kriminal",
  "Käanga",
  "L'Araignée",
  "Lady Death",
  "Lash Larue",
  "Lassie",
  "Latter",
  "Leave it to Binky",
  "Legion of Super-Heroes",
  "Les Fantastiques",
  "Les Pieds Nickelés",
  "Li'l Abner",
  "Li'l Jinx",
  "Life With Archie",
  "Linke Loetje",
  "Little Archie",
  "Little Audrey",
  "Little Dot",
  "Little Lotta",
  "Little Lulu",
  "Little Orphan Annie",
  "Littleton Stamp Co.",
  "Lobo",
  "Locas",
  "Lois Lane",
  "Los 4 Fantásticos",
  "Los Vengadores",
  "Lucky Luke",
  "Ludo",
  "Lunch",
  "Léo bête à part",
  "Man-Thing",
  "Mandrake",
  "Mandrake the Magician",
  "Marmaduke",
  "Martin Mystère",
  "Marvel Bullpen Bulletins",
  "Master of Kung Fu",
  "Meanwhile...",
  "Metropolis Mailbag",
  "Mickey Mouse",
  "Mickey à travers les siècles",
  "Mighty Mouse",
  "Miki-bøkene",
  "Miks & Tips",
  "Millie The Model",
  "MiracleMan",
  "Mister No",
  "Modesty Blaise",
  "Moon Knight",
  "Moose",
  "Mr. Weatherbee",
  "Ms. Marvel",
  "Mutt & Jeff",
  "Nancy",
  "Napoleon",
  "Naruto",
  "National Radio Institute",
  "Nemi",
  "Neste uke",
  "New Gods",
  "New Mutants",
  "New Teen Titans",
  "New Warriors",
  "Nexus",
  "Nick Fury, Agent of S.H.I.E.L.D.",
  "Nightwing",
  "Ninja High School",
  "Noortje",
  "Nova",
  "Nr. 91 Stomperud",
  "Nyoka the Jungle Girl",
  "Oktoknopie",
  "On The Ledge",
  "Oom Dagobert",
  "Palisades Amusement Park",
  "Paperino",
  "Pato Donald",
  "Patsy and Hedy",
  "Patsy Walker",
  "Peanuts",
  "Peter Porkchops",
  "Phantom",
  "Pif",
  "Pifou",
  "Pippo",
  "Placid et Muzo",
  "Planet of the Apes",
  "Plastic Man",
  "Pluto",
  "Pogo",
  "Pondus",
  "Popeye",
  "Porky Pig",
  "Preacher",
  "Premieoppgave",
  "Prince Valiant",
  "Punisher",
  "Pytonposten",
  "Quantum and Woody",
  "Ranma 1/2",
  "Rawhide Kid",
  "Red Ryder",
  "Red Sonja",
  "Reggie",
  "Reggie and Me",
  "Richie Rich",
  "Ringo Kid",
  "Rip Kirby",
  "Robin",
  "Robin Hood",
  "Rocketeer",
  "Rocky",
  "Rocky Lane",
  "Rogue Trooper",
  "Roy Rogers",
  "Rutetid",
  "Sabrina",
  "Sad Sack",
  "Sandman",
  "Savage Dragon",
  "Scamp",
  "Scooby-Doo",
  "Scribbly",
  "Seriemagasinet",
  "Sgt. Fury",
  "Sgt. Rock",
  "Shadowman",
  "Shazam!",
  "She-Hulk",
  "Sheena",
  "Sherlock Holmes",
  "Shorty",
  "Sigmund",
  "Silver Surfer",
  "Simpsons",
  "Sjors en Sjimmie",
  "Slaine",
  "Smith Brothers Cough Drops",
  "Smokey Stover",
  "Snippers",
  "Sonic the Hedgehog",
  "Spawn",
  "Spider-Man",
  "Spider-Woman",
  "Spiderman",
  "Spirit",
  "Spirou et Fantasio",
  "Spooky",
  "Star Trek",
  "Star Trek: The Next Generation",
  "Star Wars",
  "Starman",
  "Stephens Credit Sales",
  "Steve Canyon",
  "Storm",
  "Strangers In Paradise",
  "Strontium Dog",
  "Sub-Mariner",
  "Sugar & Spike",
  "Suicide Squad",
  "Super Duck",
  "Superboy",
  "Supergirl",
  "Superman",
  "Superman and Batman",
  "Superman; Batman",
  "Supermann",
  "Suske en Wiske",
  "Suus & Sas",
  "Suzie",
  "Swamp Thing",
  "Tales of Asgard",
  "Tales of the Legion of Super-Heroes",
  "Tank Girl",
  "Tarzan",
  "Teen Titans",
  "Teenage Mutant Ninja Turtles",
  "Terry and the Pirates",
  "Tex",
  "Tex Willer",
  "Texas",
  "That Wilkin Boy",
  "The Adventures of Bob Hope",
  "The Archies",
  "The Atom",
  "The Avengers",
  "The Defenders",
  "The Flash",
  "The Flintstones",
  "The Fox and the Crow",
  "The Green Arrow",
  "The Haunted Tank",
  "The Hulk",
  "The Lone Ranger",
  "The Phantom",
  "The Shadow",
  "The Spectre",
  "The Spirit",
  "The Walking Dead",
  "Thom McAn",
  "Thor",
  "Thorgal",
  "Thunderbolts",
  "Timmy the Timid Ghost",
  "Tintin",
  "Tiny Titans",
  "Titans",
  "Tom & Jerry",
  "Tom and Jerry",
  "Tom Mix",
  "Tomahawk",
  "Tomb of Dracula",
  "Tomb Raider",
  "Tootsie Roll",
  "Tootsie Roll Fudge",
  "Tootsie Roll Pop",
  "Topolino",
  "Transformers",
  "Tubby",
  "Turok",
  "Tweety and Sylvester",
  "Two-Gun Kid",
  "Uncle Scrooge",
  "Urbanus",
  "Usagi Yojimbo",
  "Vader & zoon",
  "Vampirella",
  "Vanessa",
  "Venom",
  "Veronica",
  "Warlord",
  "Watchmen",
  "Weird War Tales",
  "Wendy",
  "Wheaties",
  "Who's Who",
  "Wilbur",
  "Wildroot Cream-Oil",
  "Willems Wereld",
  "Wilson Chemical Co.",
  "Witchblade",
  "Wizard of ID",
  "Wolverine",
  "Wonder Woman",
  "Woody Woodpecker",
  "Wyatt Earp",
  "X-Factor",
  "X-Force",
  "X-Men",
  "X-O Manowar",
  "XIII",
  "Yogi Bear",
  "Zenith Company",
  "Zio Paperone",
  "Zits",
  "Zorro",
  "Zusje"
];

module.exports = charactersList;
