/* LOCAL DRAFTS  */
exports.CREATE_DRAFT = "CREATE_DRAFT";
exports.UPDATE_DRAFT = "UPDATE_DRAFT";
exports.UPDATE_DRAFT_FIELD = "UPDATE_DRAFT_FIELD";
exports.DELETE_DRAFT = "DELETE_DRAFT";

/* LINNWORKS INVENTORY UPDATES */
exports.CREATE_ITEM = "CREATE_ITEM";
exports.UPDATE_ITEM_FIELD = "UPDATE_ITEM_FIELD";
exports.UPDATE_LOCATION_FIELD = "UPDATE_LOCATION_FIELD";
exports.UPDATE_PRICE_FIELD = "UPDATE_PRICE_FIELD";
exports.ADD_PRICE_FIELD = "ADD_PRICE_FIELD";

/* REPRICER */
exports.REPRICE_ITEM = "REPRICE_ITEM";
exports.CREATE_ITEM_EXTENDED_PROPERTIES = "CREATE_ITEM_EXTENDED_PROPERTIES";
exports.UPDATE_ITEM_EXTENDED_PROPERTIES = "UPDATE_ITEM_EXTENDED_PROPERTIES";
exports.UPDATE_INVENTORY_ITEM_PRICES = "UPDATE_INVENTORY_ITEM_PRICES";
exports.ADJUST_TEMPLATE_INSTANT = "ADJUST_TEMPLATE_INSTANT";

/* PRICE MATCHING */
exports.CREATE_ISSUE_MATCH = "CREATE_ISSUE_MATCH";
exports.UPDATE_ISSUE_MATCH = "UPDATE_ISSUE_MATCH";
exports.DELETE_ISSUE_MATCH = "DELETE_ISSUE_MATCH";

/* USER ACCOUNT */
exports.UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";
