/* LOCAL DRAFTS  */
exports.CREATE_DRAFT = "CREATE_DRAFT";
exports.UPDATE_DRAFT = "UPDATE_DRAFT";
exports.UPDATE_DRAFT_FIELD = "UPDATE_DRAFT_FIELD";
exports.DELETE_DRAFT = "DELETE_DRAFT";

/* LINNWORKS INVENTORY UPDATES */
exports.CREATE_ITEM = "CREATE_ITEM";
exports.UPDATE_ITEM_FIELD = "UPDATE_ITEM_FIELD";
exports.UPDATE_LOCATION_FIELD = "UPDATE_LOCATION_FIELD";
exports.UPDATE_PRICE_FIELD = "UPDATE_PRICE_FIELD";
exports.ADD_PRICE_FIELD = "ADD_PRICE_FIELD";
exports.DELETE_DECLINE_PRICE_FIELD = "DELETE_DECLINE_PRICE_FIELD";

/* REPRICER */
exports.REPRICE_ITEM = "REPRICE_ITEM";
exports.CREATE_ITEM_EXTENDED_PROPERTIES = "CREATE_ITEM_EXTENDED_PROPERTIES";
exports.UPDATE_ITEM_EXTENDED_PROPERTIES = "UPDATE_ITEM_EXTENDED_PROPERTIES";
exports.UPDATE_INVENTORY_ITEM_PRICES = "UPDATE_INVENTORY_ITEM_PRICES";
exports.UPDATE_INVENTORY_ITEM_TITLES = "UPDATE_INVENTORY_ITEM_TITLES";
exports.ADJUST_TEMPLATE_INSTANT = "ADJUST_TEMPLATE_INSTANT";

/* PRICE MATCHING */
exports.CREATE_ISSUE_MATCH = "CREATE_ISSUE_MATCH";
exports.UPDATE_ISSUE_MATCH = "UPDATE_ISSUE_MATCH";
exports.DELETE_ISSUE_MATCH = "DELETE_ISSUE_MATCH";

/* USER ACCOUNT */
exports.UPDATE_USER_ACCOUNT = "UPDATE_USER_ACCOUNT";

/* REPACKING SERVICE */
exports.ZERO_OUT_INVENTORY = "ZERO_OUT_INVENTORY";
exports.ADD_EXTENDED_PROPERTY_FLAG = "ADD_EXTENDED_PROPERTY_FLAG";
exports.SUBMIT_FOR_REPACKING = "SUBMIT_FOR_REPACKING";
exports.FINALIZE_FOR_REPACKING = "FINALIZE_FOR_REPACKING";

exports.ADD_USER_TARGET = "ADD_USER_TARGET";
exports.UPDATE_USER_TARGET = "UPDATE_USER_TARGET";
exports.DELETE_USER_TARGET = "DELETE_USER_TARGET";
