const mainCharactersList = [
  "Batgirl",
  "Batman",
  "Catwoman",
  "Captain America",
  "DareDevil",
  "Deadpool",
  "Deathlok",
  "Fantastic Four",
  "Flash",
  "G.I. Joe",
  "Green Lantern",
  "Hulk",
  "Lobo",
  "Iron Man",
  "Moon Knight",
  "Phantom Stranger",
  "Punisher",
  "Robin",
  "Shi",
  "Silver Surfer",
  "Spider-Man",
  "Superman",
  "Thor",
  "Wolverine",
  "Wonder Woman",
  "Xena"
];

module.exports = { mainCharactersList };
