const mainCharactersList = [
  "Batgirl",
  "Batman",
  "Catwoman",
  "Captain America",
  "Daredevil",
  "Darkness",
  "Deadpool",
  "Deathlok",
  "Fantastic Four",
  "Flash",
  "G.I. Joe",
  "Green Arrow",
  "Green Lantern",
  "Hellboy",
  "Hulk",
  "Lobo",
  "Iron Man",
  "Moon Knight",
  "Phantom",
  "Phantom Stranger",
  "Punisher",
  "Robin",
  "Shi",
  "Silver Surfer",
  "Spider-Man",
  "Spawn",
  "Superman",
  "Thor",
  "Wolverine",
  "Wonder Woman",
  "Xena",
  "X-Men"
];

module.exports = { mainCharactersList };
