/* Search Titles */
export const SEARCH_TITLES = "SEARCH_TITLES";
export const SEARCH_TITLES_RESULTS_CLEAR = "SEARCH_TITLES_RESULTS_CLEAR";
export const SEARCH_TITLES_INVENTORY = "SEARCH_TITLES_INVENTORY";
export const SEARCH_TITLES_INVENTORY_CLEAR = "SEARCH_TITLES_INVENTORY";
export const SEARCH_UPC = "SEARCH_UPC";

/* Search Issues */
export const SEARCH_ISSUES = "SEARCH_ISSUES";
export const SEARCH_ISSUES_RESULTS_CLEAR = "SEARCH_ISSUES_RESULTS_CLEAR";
/* Search Ebay Categories LOCALDB */
export const SEARCH_EBAY_CATEGORIES = "SEARCH_EBAY_CATEGORIES";
/* Save Current Draft  */
export const CURRENT_DRAFT_SAVE = "CURRENT_DRAFT_SAVE";
/* Edit Current Draft */
export const EDIT_DRAFT_FETCH = "EDIT_DRAFT_FETCH";
export const EDIT_DRAFT_SAVE = "EDIT_DRAFT_SAVE";
/* DLEETE DRAFT */
export const DELETE_DRAFT = "DELETE_DRAFT";

/*Open Drafts */
export const OPEN_DRAFTS_FETCH = "OPEN_DRAFTS_FETCH";
export const OPEN_DRAFTS_SUBMIT_DRAFT = "OPEN_DRAFTS_SUBMIT_DRAFT";
export const OPEN_DRAFTS_UPDATE_DRAFT = "OPEN_DRAFTS_UPDATE_DRAFT";
/* Inventory */
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const UPDATE_INVENTORY_ITEM_LEVELS = "UPDATE_INVENTORY_ITEM_LEVELS";
export const UPDATE_ITEM_FIELDS = "UPDATE_ITEM_FIELDS";
export const UPDATE_ITEM_PRICE = "UPDATE_ITEM_PRICE";

/* V2 IMPROVED LINNWORKS SEARCHING */
export const SEARCH_LINNWORKS_INVENTORY = "SEARCH_LINNWORKS_INVENTORY";
export const GET_SELECTED_LINNWORKS_ITEM = "GET_SELECTED_LINNWORKS_ITEM";
export const UPDATE_FIELD_SELECTED_LINNWORKS_ITEM =
  "UPDATE_FIELD_SELECTED_LINNWORKS_ITEM";

/* Ebay API */
export const SEARCH_EBAY_ACTIVE = "SEARCH_EBAY_ACTIVE";
export const SEARCH_EBAY_ENDED = "SEARCH_EBAY_ENDED";
/* Pricing Service */
export const PRICE_SEARCH = "PRICE_SEARCH";
/*Locations */
export const SEARCH_BOXES = "SEARCH_BOXES";
export const SEARCH_BOXES_PRODUCTS = "SEARCH_BOXES_PRODUCTS";

export const SEARCH_CARDS = "SEARCH_CARDS";
export const SEARCH_CARDS_PRODUCTS = "SEARCH_CARDS_PRODUCTS";

export const CREATE_BOX = "CREATE_BOX";
export const UPDATE_BOX = "UPDATE_BOX";
export const DELETE_BOX = "DELETE_BOX";
export const CREATE_CARD = "CREATE_CARD";
export const CREATE_CARDS = "CREATE_CARDS";
export const UPDATE_CARD = "UPDATE_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const SET_SELECTED_BOX = "SET_SELECTED_BOX";
export const RESET_SELECTED_BOX = "RESET_SELECTED_BOX";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const RESET_SELECTED_CARD = "RESET_SELECTED_CARD";

/* LOTS AND GTCS */
export const CURRENT_LOT_DRAFT_SAVE = "CURRENT_LOT_DRAFT_SAVE";
export const LOTS_DRAFT_TITLE_CHECK = "LOTS_DRAFT_TITLE_CHECK";
export const CURRENT_GTC_DRAFT_SAVE = "CURRENT_GTC_DRAFT_SAVE";

/*Audit Log*/
export const AUDIT_LOG_FETCH = "AUDIT_LOG_FETCH";

/* Analytics */
export const ANALYTICS_FETCH = "ANALYTICS_FETCH";

/*Title Match */
export const SEARCH_OUR_TITLES = "SEARCH_OUR_TITLES";
export const SET_OUR_SELECTED_TITLE = "SET_OUR_SELECTED_TITLE";
export const CLEAR_OUR_SELECTED_TITLE = "CLEAR_OUR_SELECTED_TITLE";
export const SEARCH_OUR_ISSUES = "SEARCH_OUR_ISSUES";
export const SEARCH_THEIR_TITLES = "SEARCH_THEIR_TITLES";
export const SET_THEIR_SELECTED_TITLE = "SET_THEIR_SELECTED_TITLE";
export const CLEAR_THEIR_SELECTED_TITLE = "CLEAR_THEIR_SELECTED_TITLE";
export const SEARCH_THEIR_ISSUES = "SEARCH_THEIR_ISSUES";
export const GET_THEIR_ISSUES_PAGE = "GET_THEIR_ISSUES_PAGE";
export const SET_OUR_SELECTED_ISSUE = "SET_OUR_SELECTED_ISSUE";
export const CLEAR_OUR_SELECTED_ISSUE = "CLEAR_OUR_SELECTED_ISSUE";
export const SET_THEIR_SELECTED_ISSUE = "SET_THEIR_SELECTED_ISSUE";
export const CLEAR_THEIR_SELECTED_ISSUE = "CLEAR_THEIR_SELECTED_ISSUE";
export const SAVE_ISSUE_MATCH = "SAVE_ISSUE_MATCH";
export const SET_OUR_FILTER_COMIC_TYPES = "SET_OUR_FILTER_COMIC_TYPES";
export const SET_OUR_FILTER_VARIANTS = "SET_OUR_FILTER_VARIANTS";
export const SET_OUR_FILTER_HAS_MATCH = "SET_OUR_FILTER_HAS_MATCH";
export const UPDATE_ISSUE_MATCH = "UPDATE_ISSUE_MATCH";
export const DELETE_ISSUE_MATCH = "DELETE_ISSUE_MATCH";
/*PriceList*/
export const SEARCH_PRICELIST = "SEARCH_PRICELIST";
export const SEARCH_PRICELIST_RESULTS_SET = "SEARCH_PRICELIST_RESULTS_SET";
export const SEARCH_PRICELIST_RESULTS_LOADING =
  "SEARCH_PRICELIST_RESULTS_LOADING";
export const GET_PRICELIST_RECORD = "GET_PRICELIST_RECORD";

/* REPORTS */
export const SEARCH_SOLD_ITEMS = "SEARCH_SOLD_ITEMS";

/* OUT OF SYNC PRICES */
export const GET_OUT_OF_SYNC_PRICES = "GET_OUT_OF_SYNC_PRICES";

/* Repricing Service */
export const SEARCH_NEED_REPRICING_ITEMS = "SEARCH_NEED_REPRICING_ITEMS";
export const SEARCH_BEEN_REPRICED_ITEMS = "SEARCH_BEEN_REPRICED_ITEMS";
export const SEARCH_IN_PROGRESS_REPRICING_ITEMS =
  "SEARCH_IN_PROGRESS_REPRICING_ITEMS";
export const SUBMIT_NEED_REPRICING_ITEM = "SUBMIT_NEED_REPRICING_ITEM";
export const SEARCH_REPRICING_LOG = "SEARCH_REPRICING_LOG";
