/* Search Titles */
export const SEARCH_TITLES = "SEARCH_TITLES";
export const SEARCH_TITLES_RESULTS_CLEAR = "SEARCH_TITLES_RESULTS_CLEAR";
/* Search Issues */
export const SEARCH_ISSUES = "SEARCH_ISSUES";
export const SEARCH_ISSUES_RESULTS_CLEAR = "SEARCH_ISSUES_RESULTS_CLEAR";
/* Search Ebay Categories LOCALDB */
export const SEARCH_EBAY_CATEGORIES = "SEARCH_EBAY_CATEGORIES";
/* Save Current Draft  */
export const CURRENT_DRAFT_SAVE = "CURRENT_DRAFT_SAVE";
/*Open Drafts */
export const OPEN_DRAFTS_FETCH = "OPEN_DRAFTS_FETCH";
export const OPEN_DRAFTS_SUBMIT_DRAFT = "OPEN_DRAFTS_SUBMIT_DRAFT";
/* Inventory */
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const UPDATE_INVENTORY_ITEM_LEVELS = "UPDATE_INVENTORY_ITEM_LEVELS";
/* Ebay API */
export const SEARCH_EBAY_ACTIVE = "SEARCH_EBAY_ACTIVE";
export const SEARCH_EBAY_ENDED = "SEARCH_EBAY_ENDED";
/* Pricing Service */
export const PRICE_SEARCH = "PRICE_SEARCH";
