/* MAIN API HANDLERS */
export const ADD_API_CALL = "ADD_API_CALL";
export const REMOVE_API_CALL = "REMOVE_API_CALL";
export const UPDATE_LOADING_SCREEN_FLAG = "UPDATE_LOADING_SCREEN_FLAG";

/* Search Titles */
export const SEARCH_TITLES_SELECTED_SET = "SEARCH_TITLES_SELECTED_SET";
export const SEARCH_TITLES_SELECTED_CLEAR = "SEARCH_TITLES_SELECTED_CLEAR";
export const SEARCH_TITLES_RESULTS_SET = "SEARCH_TITLES_RESULTS_SET";
export const SEARCH_TITLES_RESULTS_CLEAR = "SEARCH_TITLES_RESULTS_CLEAR";
export const SEARCH_TITLES_RESULTS_LOADING = "SEARCH_TITLES_RESULTS_LOADING";

/* Search Issues */
export const SEARCH_ISSUES_RESULTS_SET = "SEARCH_ISSUES_RESULTS_SET";
export const SEARCH_ISSUES_RESULTS_CLEAR = "SEARCH_ISSUES_RESULTS_CLEAR";
export const SEARCH_ISSUES_RESULTS_LOADING = "SEARCH_ISSUES_RESULTS_LOADING";
/* Search Ebay Categories */
export const SEARCH_EBAY_CATEGORIES_LOADING = "SEARCH_EBAY_CATEGORIES_LOADING";
export const SEARCH_EBAY_CATEGORIES_RESULTS = "SEARCH_EBAY_CATEGORIES_RESULTS";
export const SEARCH_EBAY_CATEGORIES_CLEAR = "SEARCH_EBAY_CATEGORIES_CLEAR";

/* Current Draft */
export const CURRENT_DRAFT_CLEAR = "CURRENT_DRAFT_CLEAR";
/* Current Draft Details */
export const CURRENT_DRAFT_UPDATE = "CURRENT_DRAFT_UPDATE";
export const CURRENT_DRAFT_SAVING = "CURRENT_DRAFT_SAVING";

/* Current Draft Title */
export const CURRENT_DRAFT_TITLE_ADD = "CURRENT_DRAFT_TITLE_ADD";
export const CURRENT_DRAFT_TITLES_REORDER = "CURRENT_DRAFT_TITLES_REORDER";
export const CURRENT_DRAFT_TITLE_REMOVE = "CURRENT_DRAFT_TITLE_REMOVE";
/* Current Draft Issues */
export const CURRENT_DRAFT_ISSUE_ADD = "CURRENT_DRAFT_ISSUE_ADD";
export const CURRENT_DRAFT_ISSUE_REMOVE = "CURRENT_DRAFT_ISSUE_REMOVE";
export const CURRENT_DRAFT_ISSUES_REORDER = "CURRENT_DRAFT_ISSUES_REORDER";
/* Current Draft Cover Photo */
export const CURRENT_DRAFT_COVER_PHOTO_SAVING =
  "CURRENT_DRAFT_COVER_PHOTO_SAVING";
export const CURRENT_DRAFT_COVER_PHOTO_UPDATE =
  "CURRENT_DRAFT_COVER_PHOTO_UPDATE";
export const CURRENT_DRAFT_COVER_PHOTO_CLEAR =
  "CURRENT_DRAFT_COVER_PHOTO_CLEAR";

/* Open Drafts */
export const OPEN_DRAFTS_RESULTS = "OPEN_DRAFTS_RESULTS";
export const OPEN_DRAFTS_LOADING = "OPEN_DRAFTS_LOADING";
export const OPEN_DRAFTS_LISTED = "OPEN_DRAFTS_LISTED";

/* Settings */
export const TOGGLE_DRAFT_DRAWER = "TOGGLE_DRAFT_DRAWER";
